import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import dynamic from "next/dynamic";
const Theme = dynamic(() => import("@/components/Theme"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Country Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <Theme>
          <Header />
          <main className="p-20">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
